/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface CircleProgress {
    'progressAmount': number;
    'progressColor': string;
    'progressLabel': string;
  }
  interface CookieConsent {
    'privacyUrl': string;
  }
  interface GameItem {
    'displayName': string;
    'image': string;
    'slug': string;
  }
  interface GamesGrid {
    'categoryName': string;
    'categoryUrl': string;
    'showCategoryBar': boolean;
  }
  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface RestartProgress {}
  interface SparkMainMenu {}
}

declare global {


  interface HTMLCircleProgressElement extends Components.CircleProgress, HTMLStencilElement {}
  var HTMLCircleProgressElement: {
    prototype: HTMLCircleProgressElement;
    new (): HTMLCircleProgressElement;
  };

  interface HTMLCookieConsentElement extends Components.CookieConsent, HTMLStencilElement {}
  var HTMLCookieConsentElement: {
    prototype: HTMLCookieConsentElement;
    new (): HTMLCookieConsentElement;
  };

  interface HTMLGameItemElement extends Components.GameItem, HTMLStencilElement {}
  var HTMLGameItemElement: {
    prototype: HTMLGameItemElement;
    new (): HTMLGameItemElement;
  };

  interface HTMLGamesGridElement extends Components.GamesGrid, HTMLStencilElement {}
  var HTMLGamesGridElement: {
    prototype: HTMLGamesGridElement;
    new (): HTMLGamesGridElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLRestartProgressElement extends Components.RestartProgress, HTMLStencilElement {}
  var HTMLRestartProgressElement: {
    prototype: HTMLRestartProgressElement;
    new (): HTMLRestartProgressElement;
  };

  interface HTMLSparkMainMenuElement extends Components.SparkMainMenu, HTMLStencilElement {}
  var HTMLSparkMainMenuElement: {
    prototype: HTMLSparkMainMenuElement;
    new (): HTMLSparkMainMenuElement;
  };
  interface HTMLElementTagNameMap {
    'circle-progress': HTMLCircleProgressElement;
    'cookie-consent': HTMLCookieConsentElement;
    'game-item': HTMLGameItemElement;
    'games-grid': HTMLGamesGridElement;
    'my-component': HTMLMyComponentElement;
    'restart-progress': HTMLRestartProgressElement;
    'spark-main-menu': HTMLSparkMainMenuElement;
  }
}

declare namespace LocalJSX {
  interface CircleProgress {
    'progressAmount'?: number;
    'progressColor'?: string;
    'progressLabel'?: string;
  }
  interface CookieConsent {
    'privacyUrl'?: string;
  }
  interface GameItem {
    'displayName'?: string;
    'image'?: string;
    'slug'?: string;
  }
  interface GamesGrid {
    'categoryName'?: string;
    'categoryUrl'?: string;
    'showCategoryBar'?: boolean;
  }
  interface MyComponent {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }
  interface RestartProgress {
    'onRestartProgress'?: (event: CustomEvent<any>) => void;
  }
  interface SparkMainMenu {}

  interface IntrinsicElements {
    'circle-progress': CircleProgress;
    'cookie-consent': CookieConsent;
    'game-item': GameItem;
    'games-grid': GamesGrid;
    'my-component': MyComponent;
    'restart-progress': RestartProgress;
    'spark-main-menu': SparkMainMenu;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'circle-progress': LocalJSX.CircleProgress & JSXBase.HTMLAttributes<HTMLCircleProgressElement>;
      'cookie-consent': LocalJSX.CookieConsent & JSXBase.HTMLAttributes<HTMLCookieConsentElement>;
      'game-item': LocalJSX.GameItem & JSXBase.HTMLAttributes<HTMLGameItemElement>;
      'games-grid': LocalJSX.GamesGrid & JSXBase.HTMLAttributes<HTMLGamesGridElement>;
      'my-component': LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
      'restart-progress': LocalJSX.RestartProgress & JSXBase.HTMLAttributes<HTMLRestartProgressElement>;
      'spark-main-menu': LocalJSX.SparkMainMenu & JSXBase.HTMLAttributes<HTMLSparkMainMenuElement>;
    }
  }
}


